// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateLocalSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLocalSession'](arg1, arg2, arg3);
}

export function CreateSSHSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateSSHSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function WriteToSession(arg1, arg2) {
  return window['go']['main']['App']['WriteToSession'](arg1, arg2);
}
