// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSession(arg1:string):Promise<void>;

export function CreateLocalSession(arg1:string,arg2:number,arg3:number):Promise<string>;

export function CreateSSHSession(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number):Promise<string>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function WriteToSession(arg1:string,arg2:string):Promise<void>;
